=== ngageoint/six-library/six/modules/c++/six.sidd/conf/schema/SIDD_V3.0.0_ISM-v201609/external/ISM-v201609/CVE/CveSchema/CVEXml.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:cve="urn:us:gov:ic:cve" xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:sch="http://purl.oclc.org/dsdl/schematron"
           xmlns:ism="urn:us:gov:ic:ism"
           elementFormDefault="qualified"
           targetNamespace="urn:us:gov:ic:cve"
           version="2.1">
   <xs:annotation>
      <xs:documentation/>
   </xs:annotation>
   <xs:import namespace="urn:us:gov:ic:ism" schemaLocation="./ISM/IC-ISM.xsd"/>
   <xs:attribute name="codespace" type="xs:string">
      <xs:annotation>
         <xs:documentation/>
      </xs:annotation>
   </xs:attribute>
   <xs:attributeGroup name="PocAttributeGroup">
      <xs:attributeGroup ref="ism:POCAttributeGroup"/>
      <xs:attributeGroup ref="ism:SecurityAttributesGroup"/>
   </xs:attributeGroup>
   <xs:element name="CVE">
      <xs:annotation>
         <xs:documentation/>
      </xs:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="cve:IRM" maxOccurs="1"/>
            <xs:element maxOccurs="1" ref="cve:Enumeration"/>
         </xs:sequence>
         <xs:attribute name="CVEVersion" use="required">
            <xs:annotation>
               <xs:documentation xml:lang="en"/>
            </xs:annotation>
            <xs:simpleType>
               <xs:restriction base="xs:decimal">
                  <xs:minInclusive value="2"/>
                  <xs:maxExclusive value="3"/>
               </xs:restriction>
            </xs:simpleType>
         </xs:attribute>
         <xs:attributeGroup ref="ism:ISMRootNodeAttributeGroup"/>
         <xs:attributeGroup ref="ism:ResourceNodeAttributeGroup"/>
         <xs:attribute name="specVersion">
            <xs:annotation>
               <xs:documentation>
                  The version of the specification that the CVE belongs to.
               </xs:documentation>
               <xs:appinfo>
                  <sch:pattern>
                     <sch:rule context="*[@specVersion]">
                        <sch:assert test="@CVEVersion &gt;= 2.1">
                           The attribute specVersion can only be used with CVE Schema version 2.1 or greater.
                        </sch:assert>
                     </sch:rule>
                  </sch:pattern>
                  <sch:pattern>
                     <sch:rule context="*[@CVEVersion &gt;= 2.1]">
                        <sch:assert test="@specVersion">
                           The attribute specVersion is required with CVE Schema version 2.1 or greater.
                        </sch:assert>
                     </sch:rule>
                  </sch:pattern>
               </xs:appinfo>
            </xs:annotation>
            <xs:simpleType>
               <xs:restriction base="xs:string">
                  <xs:pattern value="(\d{6}(\.\d{6})?(\-.{1,23})?|distSpecVersionReplace)"/>
               </xs:restriction>
            </xs:simpleType>
         </xs:attribute>
      </xs:complexType>
   </xs:element>
   <xs:element name="IRM">
      <xs:annotation>
         <xs:documentation/>
      </xs:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="cve:URN"/>
            <xs:element ref="cve:Title" minOccurs="0"/>
            <xs:element ref="cve:Description" minOccurs="0"/>
            <xs:element ref="cve:Created"/>
            <xs:element ref="cve:Source" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element name="PointOfContact" type="cve:ContactInfoType" maxOccurs="unbounded"/>
         </xs:sequence>
         <xs:attribute type="xs:integer" name="documentationSortOrder" use="optional"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="Created" type="cve:CombinedDateType"/>
   <xs:element name="Enumeration">
      <xs:annotation>
         <xs:documentation/>
      </xs:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="0" ref="cve:Term"/>
         </xs:sequence>
         <xs:attribute name="multivalue" type="xs:boolean" use="required">
            <xs:annotation>
               <xs:documentation/>
            </xs:annotation>
         </xs:attribute>
         <xs:attributeGroup ref="ism:SecurityAttributesGroup"/>
      </xs:complexType>
      <xs:unique name="TermValueUnique">
         <xs:selector xpath=".//cve:Value"/>
         <xs:field xpath="."/>
      </xs:unique>
   </xs:element>
   <xs:element name="Term">
      <xs:annotation>
         <xs:documentation/>
      </xs:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="cve:Value"/>
            <xs:element ref="cve:Description">
               <xs:annotation>
                  <xs:documentation/>
               </xs:annotation>
            </xs:element>
         </xs:sequence>
         <xs:attribute use="optional" ref="cve:codespace"/>
         <xs:attribute use="optional" name="deprecated" type="xs:date">
            <xs:annotation>
               <xs:documentation/>
            </xs:annotation>
         </xs:attribute>
         <xs:attributeGroup ref="ism:SecurityAttributesGroup"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="Value">
      <xs:annotation>
         <xs:documentation/>
      </xs:annotation>
      <xs:complexType>
         <xs:simpleContent>
            <xs:extension base="xs:token">
               <xs:attribute use="optional" name="regularExpression" type="xs:boolean">
                  <xs:annotation>
                     <xs:documentation/>
                  </xs:annotation>
               </xs:attribute>
               <xs:attributeGroup ref="ism:SecurityAttributesGroup"/>
            </xs:extension>
         </xs:simpleContent>
      </xs:complexType>
   </xs:element>
   <xs:element name="URN">
      <xs:annotation>
         <xs:documentation xml:lang="en"/>
      </xs:annotation>
      <xs:simpleType>
         <xs:restriction base="xs:anyURI">
            <xs:pattern value="urn:[A-Za-z0-9][A-Za-z0-9:\-]+"/>
         </xs:restriction>
      </xs:simpleType>
   </xs:element>
   <xs:element name="Title" type="ism:ShortStringWithSecurityType">
      <xs:annotation>
         <xs:documentation xml:lang="en"/>
      </xs:annotation>
   </xs:element>
   <xs:element name="Description" type="ism:LongStringWithSecurityType">
      <xs:annotation>
         <xs:documentation xml:lang="en"/>
      </xs:annotation>
   </xs:element>
   <xs:element name="Source">
      <xs:annotation>
         <xs:documentation xml:lang="en"/>
      </xs:annotation>
      <xs:complexType>
         <xs:simpleContent>
            <xs:extension base="xs:string">
               <xs:attribute name="href" type="xs:anyURI" use="optional">
                  <xs:annotation>
                     <xs:documentation xml:lang="en"/>
                  </xs:annotation>
               </xs:attribute>
               <xs:attributeGroup ref="ism:SecurityAttributesGroup"/>
            </xs:extension>
         </xs:simpleContent>
      </xs:complexType>
   </xs:element>
   <xs:complexType name="ContactInfoType">
      <xs:annotation>
         <xs:appinfo xml:lang="en"/>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="Name" type="ism:ShortStringType" maxOccurs="unbounded"/>
         <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element name="Phone" type="ism:ShortStringType" maxOccurs="unbounded">
               <xs:annotation>
                  <xs:appinfo xml:lang="en"/>
               </xs:annotation>
            </xs:element>
            <xs:element name="Email" type="ism:ShortStringType" maxOccurs="unbounded">
               <xs:annotation>
                  <xs:appinfo xml:lang="en"/>
               </xs:annotation>
            </xs:element>
         </xs:choice>
      </xs:sequence>
      <xs:attributeGroup ref="cve:PocAttributeGroup"/>
   </xs:complexType>
   <xs:simpleType name="CombinedDateType">
      <xs:annotation>
         <xs:documentation xml:lang="en"/>
      </xs:annotation>
      <xs:union memberTypes="xs:dateTime cve:DateHourMinType xs:date xs:gYearMonth xs:gYear"/>
   </xs:simpleType>
   <xs:simpleType name="DateHourMinType">
      <xs:restriction base="xs:string">
         <xs:pattern value="[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}(Z|[\-\+][0-9]{2}:[0-9]{2})?"/>
      </xs:restriction>
   </xs:simpleType>
</xs:schema>

=== ngageoint/six-library/six/modules/c++/six.sidd/conf/schema/external/ISM-v201609/CVE/USAgency/CVEnumAuditRoutingUnique.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--This is a generated file. DO NOT EDIT!--><cve:CVE xmlns:cve="urn:us:gov:ic:cve" xmlns:ism="urn:us:gov:ic:ism"
         xmlns:uias="urn:us:gov:ic:uias"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         ism:compliesWith="USGov USIC"
         ism:ownerProducer="USA"
         ism:classification="U"
         ism:DESVersion="201609.201707"
         ism:resourceElement="true"
         ism:ISMCATCESVersion="201609"
         CVEVersion="2.1"
         specVersion="201703.201802"
         ism:createDate="2019-12-23"
         xsi:schemaLocation="urn:us:gov:ic:cve ../CveSchema/CVEXml.xsd">

	  <cve:IRM>
		    <URN xmlns="urn:us:gov:ic:cve">urn:us:gov:ic:cvenum:usagency:auditRoutingUnique</URN>
		    <Title xmlns="urn:us:gov:ic:cve" ism:ownerProducer="USA" ism:classification="U">CVEnumAuditRoutingUnique</Title>
		    <Description xmlns="urn:us:gov:ic:cve" ism:ownerProducer="USA" ism:classification="U">All ICAS approved values for organization to which Audit Records are routed 
			that are not already in USAgency CVE.</Description>

		    <Created xmlns="urn:us:gov:ic:cve">2019-12-23T16:24:49.553Z</Created>

		    <Source xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">ICAS</Source>
		    <PointOfContact xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Name>Office IC CIO</Name>
			      <Email>ic-standards-support@iarpa.gov</Email>
		    </PointOfContact>
	  </cve:IRM>

	  <cve:Enumeration multivalue="true" ism:ownerProducer="USA" ism:classification="U"><!--Extensions beyond the USAgency List-->
		
		<Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">USAFRICOM</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">
				United States Africa Command (Type: COCOM)
			</Description>
		    </Term>
		
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">USCENTCOM</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">
				United States Central Command (Type: COCOM)
			</Description>
		    </Term>
		
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">USCYBERCOM</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">
				United States Strategic Command, US Cyber Command (Type: COCOM)
			</Description>
		    </Term>
		
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">USEUCOM</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">
				United States European Command (Type: COCOM)
			</Description>
		    </Term>
		
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">USFK</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">
				United States Pacific Command, US Forces Korea (Type: COCOM)
			</Description>
		    </Term>
		
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">USNORTHCOM</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">
				United States Northern Command (Type: COCOM)
			</Description>
		    </Term>
		
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">USPACOM</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">
				United States Pacific Command (Type: COCOM)
			</Description>
		    </Term>
		
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">USSOCOM</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">
				United States Special Operations Command (Type: COCOM)
			</Description>
		    </Term>
		
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">USSOUTHCOM</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">
				United States Southern Command (Type: COCOM)
			</Description>
		    </Term>
		
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">USSTRATCOM</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">
				United States Strategic Command (Type: COCOM)
			</Description>
		    </Term>
		
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">USTRANSCOM</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">
				United States Transportation Command (Type: COCOM)
			</Description>
		    </Term>
		
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">DARPA</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">
				Defense Advanced Research Projects Agency  (Type: DOD)
			</Description>
		    </Term>
		
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">DISA</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">
				Defense Information Systems Agency (Type: DOD)
			</Description>
		    </Term>
		
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">DODCIO</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">
				Assistant Secretary of Defense for Networks and Information Integration and DoD Chief Information Officer (Type: DOD)
			</Description>
		    </Term>
		
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">DODIG</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">
				Department of Defense Inspector General (Type: DOD)
			</Description>
		    </Term>
		
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">DODIO</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">
				Assistant to the Secretary of Defense for Intelligence Oversight (Type: DOD)
			</Description>
		    </Term>
		
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">DSS</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">
				Defense Security Service (Type: DOD)
			</Description>
		    </Term>
		
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">DTRA</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">
				Defense Threat-Reduction Agency (Type: DOD)
			</Description>
		    </Term>
		
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">JCS</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">
				Office of the Joint Chiefs of Staff (Type: DOD)
			</Description>
		    </Term>
		
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">JIDA</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">
				Joint Improvised-Threat Defeat Agency (Type: DOD)
			</Description>
		    </Term>
		
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">MDA</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">
				Missile Defense Agency (Type: DOD)
			</Description>
		    </Term>
		
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">OUSDATL</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">
				Office of the Undersecretary of Defense (Acquisition, Technology and Logistics) (Type: DOD)
			</Description>
		    </Term>
		
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">OUSDI</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">
				Office of the Undersecretary of Defense (Intelligence) (Type: DOD)
			</Description>
		    </Term>
		
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">INA</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">
				United States Department of Homeland Security, Office of Intelligence and Analysis (Type: IC)
			</Description>
		    </Term>
		
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">TSA</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">
				United States Department of Homeland Security, Transportation Security Administration (Type: IC)
			</Description>
		    </Term>		
		
	  </cve:Enumeration>
</cve:CVE>

=== ngageoint/six-library/six/modules/c++/six.sidd/conf/schema/external/ISM-v201609/CVE/ISM/CVEnumISMNonUSControls.xml
<?xml version="1.0" encoding="utf-8"?><!-- Notices - Distribution Notice: 
           This document has been approved for Public Release and is available for use without restriction.
       --><cve:CVE xmlns:cve="urn:us:gov:ic:cve" xmlns:ism="urn:us:gov:ic:ism" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ism:compliesWith="USGov USIC" ism:ownerProducer="USA" ism:classification="U" ism:DESVersion="201609.201707" ism:ISMCATCESVersion="201609" ism:resourceElement="true" CVEVersion="2.1" specVersion="201609.201707" ism:createDate="2011-09-01" xsi:schemaLocation="urn:us:gov:ic:cve ../CveSchema/CVEXml.xsd">
	
	  <cve:IRM>
		    <URN xmlns="urn:us:gov:ic:cve">urn:us:gov:ic:cvenum:ism:nonuscontrols</URN>
		    <Title xmlns="urn:us:gov:ic:cve" ism:ownerProducer="USA" ism:classification="U">CVEnumISMNonUSControls</Title>
	  	<Description xmlns="urn:us:gov:ic:cve" ism:ownerProducer="USA" ism:classification="U">NonUS Control markings supported by ISM. This CVE is used by @ism:nonUSControls.</Description>
		
		    <cve:Created>2010-06-06T20:11:00-04:00</cve:Created>
		
		    <Source ism:classification="U" ism:ownerProducer="USA" xmlns="urn:us:gov:ic:cve">ISM schema</Source>
		    <PointOfContact ism:classification="U" ism:ownerProducer="USA" xmlns="urn:us:gov:ic:cve">
         <Name>Office IC CIO</Name>
         <Email>ic-standards-support@iarpa.gov</Email>
      </PointOfContact>
	  </cve:IRM>
	
	  <cve:Enumeration multivalue="true" ism:ownerProducer="USA" ism:classification="U">
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">ATOMAL</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">NATO Atomal mark</Description>
		    </Term>
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">BOHEMIA</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">NATO Bohemia mark</Description>
		    </Term>
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">BALK</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">NATO Balk mark</Description>
		    </Term>
	  </cve:Enumeration>
	
</cve:CVE>

=== ngageoint/six-library/six/modules/c++/six.sidd/conf/schema/external/ISM-v201609/CVE/NTK/CVEnumNTKProfileDes.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Notices - Distribution Notice: 
           This document has been approved for Public Release and is available for use without restriction.
       -->
<cve:CVE xmlns:cve="urn:us:gov:ic:cve" xmlns:ism="urn:us:gov:ic:ism"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ism:compliesWith="USGov USIC" ism:ownerProducer="USA"
	ism:classification="U" ism:DESVersion="201609.201707" ism:ISMCATCESVersion="201609" ism:resourceElement="true"
	CVEVersion="2.1" specVersion="201508" ism:createDate="2011-09-01" xsi:schemaLocation="urn:us:gov:ic:cve ../CveSchema/CVEXml.xsd">

	<cve:IRM>
		<URN xmlns="urn:us:gov:ic:cve">urn:us:gov:ic:cvenum:ntk:profiledes</URN>
		<Title xmlns="urn:us:gov:ic:cve" ism:ownerProducer="USA" ism:classification="U">CVEnumNTKProfileDes</Title>
		<Description xmlns="urn:us:gov:ic:cve" ism:ownerProducer="USA" ism:classification="U">NTK profile des
			names. All NTK enterprise profile des URNs start with ‘urn:us:gov:ic:ntk:profile’. Values in this CVE
			correspond to the terminating portion of NTK profile des URNs.</Description>

		<cve:Created>2015-09-04T10:54:00-04:00</cve:Created>

		<Source ism:classification="U" ism:ownerProducer="USA" xmlns="urn:us:gov:ic:cve">NTK DES</Source>
		
		<PointOfContact ism:classification="U" ism:ownerProducer="USA" xmlns="urn:us:gov:ic:cve">
			<Name>Office of the IC CIO</Name>
			<Email>ic-standards-support@iarpa.gov</Email>
		</PointOfContact>
	</cve:IRM>

	<cve:Enumeration multivalue="false" ism:ownerProducer="USA" ism:classification="U">
		<Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			<Value ism:classification="U" ism:ownerProducer="USA">urn:us:gov:ic:ntk:profile:agencydissem</Value>
			<Description ism:classification="U" ism:ownerProducer="USA">Agency Dissem</Description>
		</Term>
		<Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			<Value ism:classification="U" ism:ownerProducer="USA">urn:us:gov:ic:ntk:profile:datasphere</Value>
			<Description ism:classification="U" ism:ownerProducer="USA">Data Sphere</Description>
		</Term>
		<Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			<Value ism:classification="U" ism:ownerProducer="USA">urn:us:gov:ic:ntk:profile:grp-ind</Value>
			<Description ism:classification="U" ism:ownerProducer="USA">Group and Individual</Description>
		</Term>
	</cve:Enumeration>

</cve:CVE>

=== ngageoint/six-library/six/modules/c++/six.sidd/conf/schema/SIDD_V3.0.0_ISM-v201609/external/ISM-v201609/CVE/ISM/CVEnumISMExemptFrom.xml
<?xml version="1.0" encoding="utf-8"?><!-- Notices - Distribution Notice: 
           This document has been approved for Public Release and is available for use without restriction.
       --><cve:CVE xmlns:cve="urn:us:gov:ic:cve" xmlns:ism="urn:us:gov:ic:ism" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ism:compliesWith="USGov USIC" ism:ownerProducer="USA" ism:classification="U" ism:DESVersion="201609.201707" ism:ISMCATCESVersion="201609" ism:resourceElement="true" CVEVersion="2.1" specVersion="201609.201707" ism:createDate="2011-09-01" xsi:schemaLocation="urn:us:gov:ic:cve ../CveSchema/CVEXml.xsd">

	  <cve:IRM>
		    <URN xmlns="urn:us:gov:ic:cve">urn:us:gov:ic:cvenum:ism:exemptfrom</URN>
		    <Title xmlns="urn:us:gov:ic:cve" ism:ownerProducer="USA" ism:classification="U">CVEnumISMExemptFrom</Title>
		    <Description xmlns="urn:us:gov:ic:cve" ism:ownerProducer="USA" ism:classification="U">Current rule set names that documents may comply
		    	with. This CVE is used by @ism:exemptFrom.</Description>

		    <cve:Created>2010-05-30T16:52:00-04:00</cve:Created>

		    <Source ism:classification="U" ism:ownerProducer="USA" xmlns="urn:us:gov:ic:cve">ISM schema</Source>
		    <PointOfContact ism:classification="U" ism:ownerProducer="USA" xmlns="urn:us:gov:ic:cve">
         <Name>Office IC CIO</Name>
         <Email>ic-standards-support@iarpa.gov</Email>
      </PointOfContact>
	  </cve:IRM>

	  <cve:Enumeration multivalue="true" ism:ownerProducer="USA" ism:classification="U">
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">IC_710_MANDATORY_FDR</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">Document claims exemption from ICD-710 rules mandating the
				use of Foreign Disclosure and Release markings that have been encoded in ISM.
				Currently, the requirement for FD&amp;R is only mandatory for Disseminated Analytic
				Product; however, it is strongly encouraged otherwise.</Description>
		    </Term>
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">DOD_DISTRO_STATEMENT</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">Document claims exemption from the rules in DoD5230.24
				requiring DoD Distribution Statements that have been encoded into
				ISM.</Description>
		    </Term>
	  </cve:Enumeration>

</cve:CVE>

=== ngageoint/six-library/six/modules/c++/six.sidd/conf/schema/SIDD_V3.0.0_ISM-v201609/external/ISM-v201609/CVE/ISM/CVEnumISMClassificationAll.xml
<?xml version="1.0" encoding="utf-8"?><cve:CVE xmlns:cve="urn:us:gov:ic:cve" xmlns:ism="urn:us:gov:ic:ism" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ism:compliesWith="USGov USIC" ism:ownerProducer="USA" ism:classification="U" ism:DESVersion="201609.201707" ism:ISMCATCESVersion="201609" ism:resourceElement="true" CVEVersion="2.1" specVersion="201609.201707" ism:createDate="2011-09-01" xsi:schemaLocation="urn:us:gov:ic:cve ../CveSchema/CVEXml.xsd">

   <cve:IRM>
      <URN xmlns="urn:us:gov:ic:cve">urn:us:gov:ic:cvenum:ism:classification:all</URN>
      <Title xmlns="urn:us:gov:ic:cve" ism:ownerProducer="USA" ism:classification="U">CVEnumISMClassificationAll</Title>
      <Description xmlns="urn:us:gov:ic:cve" ism:ownerProducer="USA" ism:classification="U">All currently valid classification marks. This CVE is used by @ism:classification.</Description>
      <cve:Created>2010-05-31T21:22:00-04:00</cve:Created>
      <Source ism:classification="U" ism:ownerProducer="USA" xmlns="urn:us:gov:ic:cve">IC Systems Register and Manual</Source>
      <PointOfContact ism:classification="U" ism:ownerProducer="USA" xmlns="urn:us:gov:ic:cve">
         <Name>Office IC CIO</Name>
         <Email>ic-standards-support@iarpa.gov</Email>
      </PointOfContact>
   </cve:IRM>

   <cve:Enumeration multivalue="false" ism:ownerProducer="USA" ism:classification="U">
      <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
         <Value ism:classification="U" ism:ownerProducer="USA">R</Value>
         <Description ism:classification="U" ism:ownerProducer="USA">RESTRICTED</Description>
      </Term>
      <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
         <Value ism:classification="U" ism:ownerProducer="USA">C</Value>
         <Description ism:classification="U" ism:ownerProducer="USA">CONFIDENTIAL</Description>
      </Term>
      <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
         <Value ism:classification="U" ism:ownerProducer="USA">S</Value>
         <Description ism:classification="U" ism:ownerProducer="USA">SECRET</Description>
      </Term>
      <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
         <Value ism:classification="U" ism:ownerProducer="USA">TS</Value>
         <Description ism:classification="U" ism:ownerProducer="USA">TOP SECRET</Description>
      </Term>
      <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
         <Value ism:classification="U" ism:ownerProducer="USA">U</Value>
         <Description ism:classification="U" ism:ownerProducer="USA">UNCLASSIFIED</Description>
      </Term>
   </cve:Enumeration>
</cve:CVE>
