=== ngageoint/six-library/six/modules/c++/six.sidd/conf/schema/SIDD_V3.0.0_ISM-v201609/external/ISM-v201609/CVE/CveSchema/CVEXml.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:cve="urn:us:gov:ic:cve" xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:sch="http://purl.oclc.org/dsdl/schematron"
           xmlns:ism="urn:us:gov:ic:ism"
           elementFormDefault="qualified"
           targetNamespace="urn:us:gov:ic:cve"
           version="2.1">
   <xs:annotation>
      <xs:documentation/>
   </xs:annotation>
   <xs:import namespace="urn:us:gov:ic:ism" schemaLocation="./ISM/IC-ISM.xsd"/>
   <xs:attribute name="codespace" type="xs:string">
      <xs:annotation>
         <xs:documentation/>
      </xs:annotation>
   </xs:attribute>
   <xs:attributeGroup name="PocAttributeGroup">
      <xs:attributeGroup ref="ism:POCAttributeGroup"/>
      <xs:attributeGroup ref="ism:SecurityAttributesGroup"/>
   </xs:attributeGroup>
   <xs:element name="CVE">
      <xs:annotation>
         <xs:documentation/>
      </xs:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="cve:IRM" maxOccurs="1"/>
            <xs:element maxOccurs="1" ref="cve:Enumeration"/>
         </xs:sequence>
         <xs:attribute name="CVEVersion" use="required">
            <xs:annotation>
               <xs:documentation xml:lang="en"/>
            </xs:annotation>
            <xs:simpleType>
               <xs:restriction base="xs:decimal">
                  <xs:minInclusive value="2"/>
                  <xs:maxExclusive value="3"/>
               </xs:restriction>
            </xs:simpleType>
         </xs:attribute>
         <xs:attributeGroup ref="ism:ISMRootNodeAttributeGroup"/>
         <xs:attributeGroup ref="ism:ResourceNodeAttributeGroup"/>
         <xs:attribute name="specVersion">
            <xs:annotation>
               <xs:documentation>
                  The version of the specification that the CVE belongs to.
               </xs:documentation>
               <xs:appinfo>
                  <sch:pattern>
                     <sch:rule context="*[@specVersion]">
                        <sch:assert test="@CVEVersion &gt;= 2.1">
                           The attribute specVersion can only be used with CVE Schema version 2.1 or greater.
                        </sch:assert>
                     </sch:rule>
                  </sch:pattern>
                  <sch:pattern>
                     <sch:rule context="*[@CVEVersion &gt;= 2.1]">
                        <sch:assert test="@specVersion">
                           The attribute specVersion is required with CVE Schema version 2.1 or greater.
                        </sch:assert>
                     </sch:rule>
                  </sch:pattern>
               </xs:appinfo>
            </xs:annotation>
            <xs:simpleType>
               <xs:restriction base="xs:string">
                  <xs:pattern value="(\d{6}(\.\d{6})?(\-.{1,23})?|distSpecVersionReplace)"/>
               </xs:restriction>
            </xs:simpleType>
         </xs:attribute>
      </xs:complexType>
   </xs:element>
   <xs:element name="IRM">
      <xs:annotation>
         <xs:documentation/>
      </xs:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="cve:URN"/>
            <xs:element ref="cve:Title" minOccurs="0"/>
            <xs:element ref="cve:Description" minOccurs="0"/>
            <xs:element ref="cve:Created"/>
            <xs:element ref="cve:Source" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element name="PointOfContact" type="cve:ContactInfoType" maxOccurs="unbounded"/>
         </xs:sequence>
         <xs:attribute type="xs:integer" name="documentationSortOrder" use="optional"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="Created" type="cve:CombinedDateType"/>
   <xs:element name="Enumeration">
      <xs:annotation>
         <xs:documentation/>
      </xs:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="0" ref="cve:Term"/>
         </xs:sequence>
         <xs:attribute name="multivalue" type="xs:boolean" use="required">
            <xs:annotation>
               <xs:documentation/>
            </xs:annotation>
         </xs:attribute>
         <xs:attributeGroup ref="ism:SecurityAttributesGroup"/>
      </xs:complexType>
      <xs:unique name="TermValueUnique">
         <xs:selector xpath=".//cve:Value"/>
         <xs:field xpath="."/>
      </xs:unique>
   </xs:element>
   <xs:element name="Term">
      <xs:annotation>
         <xs:documentation/>
      </xs:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="cve:Value"/>
            <xs:element ref="cve:Description">
               <xs:annotation>
                  <xs:documentation/>
               </xs:annotation>
            </xs:element>
         </xs:sequence>
         <xs:attribute use="optional" ref="cve:codespace"/>
         <xs:attribute use="optional" name="deprecated" type="xs:date">
            <xs:annotation>
               <xs:documentation/>
            </xs:annotation>
         </xs:attribute>
         <xs:attributeGroup ref="ism:SecurityAttributesGroup"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="Value">
      <xs:annotation>
         <xs:documentation/>
      </xs:annotation>
      <xs:complexType>
         <xs:simpleContent>
            <xs:extension base="xs:token">
               <xs:attribute use="optional" name="regularExpression" type="xs:boolean">
                  <xs:annotation>
                     <xs:documentation/>
                  </xs:annotation>
               </xs:attribute>
               <xs:attributeGroup ref="ism:SecurityAttributesGroup"/>
            </xs:extension>
         </xs:simpleContent>
      </xs:complexType>
   </xs:element>
   <xs:element name="URN">
      <xs:annotation>
         <xs:documentation xml:lang="en"/>
      </xs:annotation>
      <xs:simpleType>
         <xs:restriction base="xs:anyURI">
            <xs:pattern value="urn:[A-Za-z0-9][A-Za-z0-9:\-]+"/>
         </xs:restriction>
      </xs:simpleType>
   </xs:element>
   <xs:element name="Title" type="ism:ShortStringWithSecurityType">
      <xs:annotation>
         <xs:documentation xml:lang="en"/>
      </xs:annotation>
   </xs:element>
   <xs:element name="Description" type="ism:LongStringWithSecurityType">
      <xs:annotation>
         <xs:documentation xml:lang="en"/>
      </xs:annotation>
   </xs:element>
   <xs:element name="Source">
      <xs:annotation>
         <xs:documentation xml:lang="en"/>
      </xs:annotation>
      <xs:complexType>
         <xs:simpleContent>
            <xs:extension base="xs:string">
               <xs:attribute name="href" type="xs:anyURI" use="optional">
                  <xs:annotation>
                     <xs:documentation xml:lang="en"/>
                  </xs:annotation>
               </xs:attribute>
               <xs:attributeGroup ref="ism:SecurityAttributesGroup"/>
            </xs:extension>
         </xs:simpleContent>
      </xs:complexType>
   </xs:element>
   <xs:complexType name="ContactInfoType">
      <xs:annotation>
         <xs:appinfo xml:lang="en"/>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="Name" type="ism:ShortStringType" maxOccurs="unbounded"/>
         <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element name="Phone" type="ism:ShortStringType" maxOccurs="unbounded">
               <xs:annotation>
                  <xs:appinfo xml:lang="en"/>
               </xs:annotation>
            </xs:element>
            <xs:element name="Email" type="ism:ShortStringType" maxOccurs="unbounded">
               <xs:annotation>
                  <xs:appinfo xml:lang="en"/>
               </xs:annotation>
            </xs:element>
         </xs:choice>
      </xs:sequence>
      <xs:attributeGroup ref="cve:PocAttributeGroup"/>
   </xs:complexType>
   <xs:simpleType name="CombinedDateType">
      <xs:annotation>
         <xs:documentation xml:lang="en"/>
      </xs:annotation>
      <xs:union memberTypes="xs:dateTime cve:DateHourMinType xs:date xs:gYearMonth xs:gYear"/>
   </xs:simpleType>
   <xs:simpleType name="DateHourMinType">
      <xs:restriction base="xs:string">
         <xs:pattern value="[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}(Z|[\-\+][0-9]{2}:[0-9]{2})?"/>
      </xs:restriction>
   </xs:simpleType>
</xs:schema>

=== ngageoint/six-library/six/modules/c++/six.sidd/conf/schema/SIDD_V3.0.0_ISM-v201609/external/ISM-v201609/CVE/ISM/CVEnumISMDissem.xml
<?xml version="1.0" encoding="utf-8"?><!-- Notices - Distribution Notice: 
           This document has been approved for Public Release and is available for use without restriction.
       --><cve:CVE xmlns:cve="urn:us:gov:ic:cve" xmlns:ism="urn:us:gov:ic:ism" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ism:compliesWith="USGov USIC" ism:ownerProducer="USA" ism:classification="U" ism:DESVersion="201609.201707" ism:ISMCATCESVersion="201609" ism:resourceElement="true" CVEVersion="2.1" specVersion="201609.201707" ism:createDate="2012-01-04" xsi:schemaLocation="urn:us:gov:ic:cve ../CveSchema/CVEXml.xsd">


	  <cve:IRM>
		    <URN xmlns="urn:us:gov:ic:cve">urn:us:gov:ic:cvenum:ism:dissem</URN>
		    <Title xmlns="urn:us:gov:ic:cve" ism:ownerProducer="USA" ism:classification="U">CVEnumISMDissem</Title>
	  	<Description xmlns="urn:us:gov:ic:cve" ism:ownerProducer="USA" ism:classification="U">All currently valid Dissemination controls from the published register. This CVE is used by @ism:disseminationControls.</Description>
		    <cve:Created>2012-01-04T00:14:00-04:00</cve:Created>
		    <Source ism:classification="U" ism:ownerProducer="USA" xmlns="urn:us:gov:ic:cve">IC Systems Register and Manual</Source>
		    <PointOfContact ism:classification="U" ism:ownerProducer="USA" xmlns="urn:us:gov:ic:cve">
         <Name>Office IC CIO</Name>
         <Email>ic-standards-support@iarpa.gov</Email>
      </PointOfContact>
	  </cve:IRM>
	
	  <cve:Enumeration multivalue="true" ism:ownerProducer="USA" ism:classification="U">
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">RS</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">RISK SENSITIVE</Description>
		    </Term>
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">FOUO</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">FOR OFFICIAL USE ONLY</Description>
		    </Term>
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">OC</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">ORIGINATOR CONTROLLED</Description>
		    </Term>
		  	<Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
		  		   <Value ism:classification="U" ism:ownerProducer="USA">OC-USGOV</Value>
		  		   <Description ism:classification="U" ism:ownerProducer="USA">ORIGINATOR CONTROLLED US GOVERNMENT</Description>
		  	</Term>
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">IMC</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">CONTROLLED IMAGERY</Description>
		    </Term>
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">NF</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">NOT RELEASABLE TO FOREIGN NATIONALS</Description>
		    </Term>
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">PR</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">CAUTION-PROPRIETARY INFORMATION INVOLVED</Description>
		    </Term>
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">REL</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">AUTHORIZED FOR RELEASE TO</Description>
		    </Term>
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">RELIDO</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">RELEASABLE BY INFORMATION DISCLOSURE OFFICIAL</Description>
		    </Term>
	  	  <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA" deprecated="2017-11-01">
			      <Value ism:classification="U" ism:ownerProducer="USA">EYES</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">EYES ONLY</Description>
		    </Term>
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">DSEN</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">DEA SENSITIVE</Description>
		    </Term>
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">FISA</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">FOREIGN INTELLIGENCE SURVEILLANCE ACT</Description>
		    </Term>
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">DISPLAYONLY</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">AUTHORIZED FOR DISPLAY BUT NOT RELEASE TO</Description>
		    </Term>
	  </cve:Enumeration>
</cve:CVE>

=== ngageoint/six-library/six/modules/c++/six.sidd/conf/schema/SIDD_V3.0.0_ISM-v201609/external/ISM-v201609/CVE/ISM/CVEnumISMAtomicEnergyMarkings.xml
<?xml version="1.0" encoding="utf-8"?><!-- Notices - Distribution Notice: 
           This document has been approved for Public Release and is available for use without restriction.
       --><cve:CVE xmlns:cve="urn:us:gov:ic:cve" xmlns:ism="urn:us:gov:ic:ism" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ism:compliesWith="USGov USIC" ism:ownerProducer="USA" ism:classification="U" ism:DESVersion="201609.201707" ism:ISMCATCESVersion="201609" ism:resourceElement="true" CVEVersion="2.1" specVersion="201609.201707" ism:createDate="2011-09-01" xsi:schemaLocation="urn:us:gov:ic:cve ../CveSchema/CVEXml.xsd">
    
    <cve:IRM>
        <URN xmlns="urn:us:gov:ic:cve">urn:us:gov:ic:cvenum:ism:atomicEnergyMarkings</URN>
        <Title xmlns="urn:us:gov:ic:cve" ism:ownerProducer="USA" ism:classification="U">CVEnumISMatomicEnergyMarkings</Title>
        <Description xmlns="urn:us:gov:ic:cve" ism:ownerProducer="USA" ism:classification="U">All currently valid Atomic Energy information markings from the published register. This CVE is used by @ism:atomicEnergyMarkings.</Description>
        
        <cve:Created>2011-02-04T00:22:00-04:00</cve:Created>
        
        <Source ism:classification="U" ism:ownerProducer="USA" xmlns="urn:us:gov:ic:cve">IC Systems Register and Manual</Source>
        <PointOfContact ism:classification="U" ism:ownerProducer="USA" xmlns="urn:us:gov:ic:cve">
         <Name>Office IC CIO</Name>
         <Email>ic-standards-support@iarpa.gov</Email>
      </PointOfContact>
    </cve:IRM>
    
    <cve:Enumeration multivalue="true" ism:ownerProducer="USA" ism:classification="U">
        
        <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
            <Value ism:classification="U" ism:ownerProducer="USA">RD</Value>
            <Description ism:classification="U" ism:ownerProducer="USA">RESTRICTED DATA</Description>
        </Term>
        <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
            <Value ism:classification="U" ism:ownerProducer="USA">RD-CNWDI</Value>
            <Description ism:classification="U" ism:ownerProducer="USA">RD-CRITICAL NUCLEAR WEAPON DESIGN INFORMATION</Description>
        </Term>
        <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
            <Value ism:classification="U" ism:ownerProducer="USA" regularExpression="true">RD-SG-((14)|(15)|(18)|(20))</Value>
            <Description ism:classification="U" ism:ownerProducer="USA">RD-SIGMA-#, # represents the SIGMA number which may be 14, 15, 18, or 20.</Description>
        </Term>
        <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
            <Value ism:classification="U" ism:ownerProducer="USA">FRD</Value>
            <Description ism:classification="U" ism:ownerProducer="USA">FORMERLY RESTRICTED DATA</Description>
        </Term>
        <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
            <Value ism:classification="U" ism:ownerProducer="USA" regularExpression="true">FRD-SG-((14)|(15)|(18)|(20))</Value>
            <Description ism:classification="U" ism:ownerProducer="USA">FRD-SIGMA-#, # represents the SIGMA number which may be 14, 15, 18, or 20.</Description>
        </Term>
        <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
            <Value ism:classification="U" ism:ownerProducer="USA">DCNI</Value>
            <Description ism:classification="U" ism:ownerProducer="USA">DoD CONTROLLED NUCLEAR INFORMATION</Description>
        </Term>
        <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
            <Value ism:classification="U" ism:ownerProducer="USA">UCNI</Value>
            <Description ism:classification="U" ism:ownerProducer="USA">DoE CONTROLLED NUCLEAR INFORMATION</Description>
        </Term>
        <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
            <Value ism:classification="U" ism:ownerProducer="USA">TFNI</Value>
            <Description ism:classification="U" ism:ownerProducer="USA">TRANSCLASSIFIED FOREIGN NUCLEAR INFORMATION</Description>
        </Term>
    </cve:Enumeration>
    
</cve:CVE>

=== ngageoint/six-library/six/modules/c++/six.sidd/conf/schema/external/ISM-v201609/CVE/ISM/CVEnumISMNonIC.xml
<?xml version="1.0" encoding="utf-8"?><!-- Notices - Distribution Notice: 
           This document has been approved for Public Release and is available for use without restriction.
       --><cve:CVE xmlns:cve="urn:us:gov:ic:cve" xmlns:ism="urn:us:gov:ic:ism" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ism:compliesWith="USGov USIC" ism:ownerProducer="USA" ism:classification="U" ism:DESVersion="201609.201707" ism:ISMCATCESVersion="201609" ism:resourceElement="true" CVEVersion="2.1" specVersion="201609.201707" ism:createDate="2012-01-04" xsi:schemaLocation="urn:us:gov:ic:cve ../CveSchema/CVEXml.xsd">
	
	  <cve:IRM>
		    <URN xmlns="urn:us:gov:ic:cve">urn:us:gov:ic:cvenum:ism:nonic</URN>
		    <Title xmlns="urn:us:gov:ic:cve" ism:ownerProducer="USA" ism:classification="U">CVEnumISMNonIC</Title>
	  	<Description xmlns="urn:us:gov:ic:cve" ism:ownerProducer="USA" ism:classification="U">All currently valid Non-IC markings from the published register. This CVE is used by @ism:nonICmarkings.</Description>
		
		    <cve:Created>2012-01-04T00:14:00-04:00</cve:Created>
		
		    <Source ism:classification="U" ism:ownerProducer="USA" xmlns="urn:us:gov:ic:cve">IC Systems Register and Manual</Source>
		    <PointOfContact ism:classification="U" ism:ownerProducer="USA" xmlns="urn:us:gov:ic:cve">
         <Name>Office IC CIO</Name>
         <Email>ic-standards-support@iarpa.gov</Email>
      </PointOfContact>
	  </cve:IRM>
	
	  <cve:Enumeration multivalue="true" ism:ownerProducer="USA" ism:classification="U">
		
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">DS</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">LIMITED DISTRIBUTION</Description>
		    </Term>
	  		<!--	  	
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA" regularExpression="true">ACCM-[A-Z0-9\-_]{1,61}</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">The name of the ALTERNATE COMPENSATORY CONTROL MEASURE, substituting "_" for a space.</Description>
		    </Term>
			-->		
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">XD</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">EXCLUSIVE DISTRIBUTION</Description>
		    </Term>
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">ND</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">NO DISTRIBUTION</Description>
		    </Term>
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">SBU</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">SENSITIVE BUT UNCLASSIFIED</Description>
		    </Term>
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">SBU-NF</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">SENSITIVE BUT UNCLASSIFIED NOFORN</Description>
		    </Term>
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">LES</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">LAW ENFORCEMENT SENSITIVE</Description>
		    </Term>
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">LES-NF</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">LAW ENFORCEMENT SENSITIVE NOFORN</Description>
		    </Term>
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">SSI</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">SENSITIVE SECURITY INFORMATION</Description>
		    </Term>    
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">NNPI</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">NAVAL NUCLEAR PROPULSION INFORMATION</Description>
		    </Term>
	  </cve:Enumeration> 
</cve:CVE>
