=== ngageoint/six-library/six/modules/c++/six.sidd/conf/schema/SIDD_V3.0.0_ISM-v201609/external/ISM-v201609/CVE/CveSchema/CVEXml.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:cve="urn:us:gov:ic:cve" xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:sch="http://purl.oclc.org/dsdl/schematron"
           xmlns:ism="urn:us:gov:ic:ism"
           elementFormDefault="qualified"
           targetNamespace="urn:us:gov:ic:cve"
           version="2.1">
   <xs:annotation>
      <xs:documentation/>
   </xs:annotation>
   <xs:import namespace="urn:us:gov:ic:ism" schemaLocation="./ISM/IC-ISM.xsd"/>
   <xs:attribute name="codespace" type="xs:string">
      <xs:annotation>
         <xs:documentation/>
      </xs:annotation>
   </xs:attribute>
   <xs:attributeGroup name="PocAttributeGroup">
      <xs:attributeGroup ref="ism:POCAttributeGroup"/>
      <xs:attributeGroup ref="ism:SecurityAttributesGroup"/>
   </xs:attributeGroup>
   <xs:element name="CVE">
      <xs:annotation>
         <xs:documentation/>
      </xs:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="cve:IRM" maxOccurs="1"/>
            <xs:element maxOccurs="1" ref="cve:Enumeration"/>
         </xs:sequence>
         <xs:attribute name="CVEVersion" use="required">
            <xs:annotation>
               <xs:documentation xml:lang="en"/>
            </xs:annotation>
            <xs:simpleType>
               <xs:restriction base="xs:decimal">
                  <xs:minInclusive value="2"/>
                  <xs:maxExclusive value="3"/>
               </xs:restriction>
            </xs:simpleType>
         </xs:attribute>
         <xs:attributeGroup ref="ism:ISMRootNodeAttributeGroup"/>
         <xs:attributeGroup ref="ism:ResourceNodeAttributeGroup"/>
         <xs:attribute name="specVersion">
            <xs:annotation>
               <xs:documentation>
                  The version of the specification that the CVE belongs to.
               </xs:documentation>
               <xs:appinfo>
                  <sch:pattern>
                     <sch:rule context="*[@specVersion]">
                        <sch:assert test="@CVEVersion &gt;= 2.1">
                           The attribute specVersion can only be used with CVE Schema version 2.1 or greater.
                        </sch:assert>
                     </sch:rule>
                  </sch:pattern>
                  <sch:pattern>
                     <sch:rule context="*[@CVEVersion &gt;= 2.1]">
                        <sch:assert test="@specVersion">
                           The attribute specVersion is required with CVE Schema version 2.1 or greater.
                        </sch:assert>
                     </sch:rule>
                  </sch:pattern>
               </xs:appinfo>
            </xs:annotation>
            <xs:simpleType>
               <xs:restriction base="xs:string">
                  <xs:pattern value="(\d{6}(\.\d{6})?(\-.{1,23})?|distSpecVersionReplace)"/>
               </xs:restriction>
            </xs:simpleType>
         </xs:attribute>
      </xs:complexType>
   </xs:element>
   <xs:element name="IRM">
      <xs:annotation>
         <xs:documentation/>
      </xs:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="cve:URN"/>
            <xs:element ref="cve:Title" minOccurs="0"/>
            <xs:element ref="cve:Description" minOccurs="0"/>
            <xs:element ref="cve:Created"/>
            <xs:element ref="cve:Source" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element name="PointOfContact" type="cve:ContactInfoType" maxOccurs="unbounded"/>
         </xs:sequence>
         <xs:attribute type="xs:integer" name="documentationSortOrder" use="optional"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="Created" type="cve:CombinedDateType"/>
   <xs:element name="Enumeration">
      <xs:annotation>
         <xs:documentation/>
      </xs:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="0" ref="cve:Term"/>
         </xs:sequence>
         <xs:attribute name="multivalue" type="xs:boolean" use="required">
            <xs:annotation>
               <xs:documentation/>
            </xs:annotation>
         </xs:attribute>
         <xs:attributeGroup ref="ism:SecurityAttributesGroup"/>
      </xs:complexType>
      <xs:unique name="TermValueUnique">
         <xs:selector xpath=".//cve:Value"/>
         <xs:field xpath="."/>
      </xs:unique>
   </xs:element>
   <xs:element name="Term">
      <xs:annotation>
         <xs:documentation/>
      </xs:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="cve:Value"/>
            <xs:element ref="cve:Description">
               <xs:annotation>
                  <xs:documentation/>
               </xs:annotation>
            </xs:element>
         </xs:sequence>
         <xs:attribute use="optional" ref="cve:codespace"/>
         <xs:attribute use="optional" name="deprecated" type="xs:date">
            <xs:annotation>
               <xs:documentation/>
            </xs:annotation>
         </xs:attribute>
         <xs:attributeGroup ref="ism:SecurityAttributesGroup"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="Value">
      <xs:annotation>
         <xs:documentation/>
      </xs:annotation>
      <xs:complexType>
         <xs:simpleContent>
            <xs:extension base="xs:token">
               <xs:attribute use="optional" name="regularExpression" type="xs:boolean">
                  <xs:annotation>
                     <xs:documentation/>
                  </xs:annotation>
               </xs:attribute>
               <xs:attributeGroup ref="ism:SecurityAttributesGroup"/>
            </xs:extension>
         </xs:simpleContent>
      </xs:complexType>
   </xs:element>
   <xs:element name="URN">
      <xs:annotation>
         <xs:documentation xml:lang="en"/>
      </xs:annotation>
      <xs:simpleType>
         <xs:restriction base="xs:anyURI">
            <xs:pattern value="urn:[A-Za-z0-9][A-Za-z0-9:\-]+"/>
         </xs:restriction>
      </xs:simpleType>
   </xs:element>
   <xs:element name="Title" type="ism:ShortStringWithSecurityType">
      <xs:annotation>
         <xs:documentation xml:lang="en"/>
      </xs:annotation>
   </xs:element>
   <xs:element name="Description" type="ism:LongStringWithSecurityType">
      <xs:annotation>
         <xs:documentation xml:lang="en"/>
      </xs:annotation>
   </xs:element>
   <xs:element name="Source">
      <xs:annotation>
         <xs:documentation xml:lang="en"/>
      </xs:annotation>
      <xs:complexType>
         <xs:simpleContent>
            <xs:extension base="xs:string">
               <xs:attribute name="href" type="xs:anyURI" use="optional">
                  <xs:annotation>
                     <xs:documentation xml:lang="en"/>
                  </xs:annotation>
               </xs:attribute>
               <xs:attributeGroup ref="ism:SecurityAttributesGroup"/>
            </xs:extension>
         </xs:simpleContent>
      </xs:complexType>
   </xs:element>
   <xs:complexType name="ContactInfoType">
      <xs:annotation>
         <xs:appinfo xml:lang="en"/>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="Name" type="ism:ShortStringType" maxOccurs="unbounded"/>
         <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element name="Phone" type="ism:ShortStringType" maxOccurs="unbounded">
               <xs:annotation>
                  <xs:appinfo xml:lang="en"/>
               </xs:annotation>
            </xs:element>
            <xs:element name="Email" type="ism:ShortStringType" maxOccurs="unbounded">
               <xs:annotation>
                  <xs:appinfo xml:lang="en"/>
               </xs:annotation>
            </xs:element>
         </xs:choice>
      </xs:sequence>
      <xs:attributeGroup ref="cve:PocAttributeGroup"/>
   </xs:complexType>
   <xs:simpleType name="CombinedDateType">
      <xs:annotation>
         <xs:documentation xml:lang="en"/>
      </xs:annotation>
      <xs:union memberTypes="xs:dateTime cve:DateHourMinType xs:date xs:gYearMonth xs:gYear"/>
   </xs:simpleType>
   <xs:simpleType name="DateHourMinType">
      <xs:restriction base="xs:string">
         <xs:pattern value="[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}(Z|[\-\+][0-9]{2}:[0-9]{2})?"/>
      </xs:restriction>
   </xs:simpleType>
</xs:schema>

=== ngageoint/six-library/six/modules/c++/six.sidd/conf/schema/external/ISM-v201609/CVE/ISM/CVEnumISMElements.xml
<?xml version="1.0" encoding="utf-8"?><!-- Notices - Distribution Notice: 
           This document has been approved for Public Release and is available for use without restriction.
       --><cve:CVE xmlns:cve="urn:us:gov:ic:cve" xmlns:ism="urn:us:gov:ic:ism" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ism:compliesWith="USGov USIC" ism:ownerProducer="USA" ism:classification="U" ism:DESVersion="201609.201707" ism:ISMCATCESVersion="201609" ism:resourceElement="true" CVEVersion="2.1" specVersion="201609.201707" ism:createDate="2011-09-01" xsi:schemaLocation="urn:us:gov:ic:cve ../CveSchema/CVEXml.xsd">
	
	  <cve:IRM>
		    <URN xmlns="urn:us:gov:ic:cve">urn:us:gov:ic:cvenum:ism:attributes</URN>
		    <Title xmlns="urn:us:gov:ic:cve" ism:ownerProducer="USA" ism:classification="U">CVEnumISMElements</Title>
		    <Description xmlns="urn:us:gov:ic:cve" ism:ownerProducer="USA" ism:classification="U">All currently authorized ISM element names</Description>
		
		    <cve:Created>2011-04-15T15:16:00-05:00</cve:Created>
		
		    <Source ism:classification="U" ism:ownerProducer="USA" xmlns="urn:us:gov:ic:cve">ISM schema</Source>
		    <PointOfContact ism:classification="U" ism:ownerProducer="USA" xmlns="urn:us:gov:ic:cve">
         <Name>Office IC CIO</Name>
         <Email>ic-standards-support@iarpa.gov</Email>
      </PointOfContact>
	  </cve:IRM>
	
	  <cve:Enumeration multivalue="false" ism:ownerProducer="USA" ism:classification="U">
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">Notice</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">Notice element</Description>
		    </Term>
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">NoticeText</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">NoticeText element</Description>
		    </Term>
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">NoticeList</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">NoticeList element</Description>
		    </Term>
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">NoticeExternal</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">NoticeExternal element</Description>
		    </Term>
		    <Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			      <Value ism:classification="U" ism:ownerProducer="USA">NoticeExternalList</Value>
			      <Description ism:classification="U" ism:ownerProducer="USA">NoticeExternalList element</Description>
		    </Term>
	  </cve:Enumeration>
	
</cve:CVE>

=== ngageoint/six-library/six/modules/c++/six.sidd/conf/schema/SIDD_V3.0.0_ISM-v201609/external/ISM-v201609/CVE/MN/CVEnumMNRegion.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-model href="../../Schematron/ISM/ISM_XML.sch" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<!-- Notices - Distribution Notice: 
           This document has been approved for Public Release and is available for use without restriction.
       -->
<cve:CVE xmlns:cve="urn:us:gov:ic:cve" xmlns:ism="urn:us:gov:ic:ism"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	ism:compliesWith="USGov USIC" ism:ownerProducer="USA" ism:classification="U" ism:DESVersion="201609.201707"
	ism:ISMCATCESVersion="201609" ism:resourceElement="true" CVEVersion="2.1" specVersion="201705"
	ism:createDate="2013-11-15"
	xsi:schemaLocation="urn:us:gov:ic:cve ../CveSchema/CVEXml.xsd">

	<cve:IRM>
		<URN xmlns="urn:us:gov:ic:cve">urn:us:gov:ic:cvenum:mn:region</URN>
		<Title xmlns="urn:us:gov:ic:cve" ism:ownerProducer="USA" ism:classification="U">CVEnumMNRegion</Title>
		<Description xmlns="urn:us:gov:ic:cve" ism:ownerProducer="USA" ism:classification="U">All 
			currently identified values for Region. This list was originally derived from the 
		    GIMMEE Mission Need Region list.</Description>

		<cve:Created>2015-06-03</cve:Created>

		<Source ism:classification="U" ism:ownerProducer="USA" xmlns="urn:us:gov:ic:cve">IC-CIO</Source>
		<PointOfContact ism:classification="U" ism:ownerProducer="USA" xmlns="urn:us:gov:ic:cve">
			<Name>Office IC CIO</Name>
			<Email>ic-standards-support@iarpa.gov</Email>
		</PointOfContact>
	</cve:IRM>

	<cve:Enumeration multivalue="false" ism:ownerProducer="USA" ism:classification="U">
		<Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			<Value ism:classification="U" ism:ownerProducer="USA">AFce</Value>
			<Description ism:classification="U" ism:ownerProducer="USA">Africa, Central</Description>
		</Term>
		<Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			<Value ism:classification="U" ism:ownerProducer="USA">AFea</Value>
			<Description ism:classification="U" ism:ownerProducer="USA">Africa, East</Description>
		</Term>
		<Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			<Value ism:classification="U" ism:ownerProducer="USA">AFno</Value>
			<Description ism:classification="U" ism:ownerProducer="USA">Africa, North</Description>
		</Term>
		<Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			<Value ism:classification="U" ism:ownerProducer="USA">AFso</Value>
			<Description ism:classification="U" ism:ownerProducer="USA">Africa, Southern</Description>
		</Term>
		<Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			<Value ism:classification="U" ism:ownerProducer="USA">AFwe</Value>
			<Description ism:classification="U" ism:ownerProducer="USA">Africa, West</Description>
		</Term>
		<Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			<Value ism:classification="U" ism:ownerProducer="USA">AMca</Value>
			<Description ism:classification="U" ism:ownerProducer="USA">Americas, Caribbean</Description>
		</Term>
		<Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			<Value ism:classification="U" ism:ownerProducer="USA">AMce</Value>
			<Description ism:classification="U" ism:ownerProducer="USA">Americas, Central</Description>
		</Term>
		<Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			<Value ism:classification="U" ism:ownerProducer="USA">AMno</Value>
			<Description ism:classification="U" ism:ownerProducer="USA">Americas, North</Description>
		</Term>
		<Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			<Value ism:classification="U" ism:ownerProducer="USA">AMso</Value>
			<Description ism:classification="U" ism:ownerProducer="USA">Americas, South</Description>
		</Term>
		<Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			<Value ism:classification="U" ism:ownerProducer="USA">AMan</Value>
			<Description ism:classification="U" ism:ownerProducer="USA">Americas, Antarctica</Description>
		</Term>
		<Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			<Value ism:classification="U" ism:ownerProducer="USA">ASea</Value>
			<Description ism:classification="U" ism:ownerProducer="USA">Asia, East</Description>
		</Term>
		<Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			<Value ism:classification="U" ism:ownerProducer="USA">ASse</Value>
			<Description ism:classification="U" ism:ownerProducer="USA">Asia, South East</Description>
		</Term>
		<Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			<Value ism:classification="U" ism:ownerProducer="USA">ASso</Value>
			<Description ism:classification="U" ism:ownerProducer="USA">Asia, South</Description>
		</Term>
		<Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			<Value ism:classification="U" ism:ownerProducer="USA">EAca</Value>
			<Description ism:classification="U" ism:ownerProducer="USA">Eurasia, Caucasus</Description>
		</Term>
		<Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			<Value ism:classification="U" ism:ownerProducer="USA">EAce</Value>
			<Description ism:classification="U" ism:ownerProducer="USA">Eurasia, Central</Description>
		</Term>
		<Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			<Value ism:classification="U" ism:ownerProducer="USA">EAru</Value>
			<Description ism:classification="U" ism:ownerProducer="USA">Eurasia, Russia</Description>
		</Term>
		<Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			<Value ism:classification="U" ism:ownerProducer="USA">EUba</Value>
			<Description ism:classification="U" ism:ownerProducer="USA">Europe, Balkans</Description>
		</Term>
		<Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			<Value ism:classification="U" ism:ownerProducer="USA">EUce</Value>
			<Description ism:classification="U" ism:ownerProducer="USA">Europe, Central</Description>
		</Term>
		<Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			<Value ism:classification="U" ism:ownerProducer="USA">EUno</Value>
			<Description ism:classification="U" ism:ownerProducer="USA">Europe, North</Description>
		</Term>
		<Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			<Value ism:classification="U" ism:ownerProducer="USA">EUso</Value>
			<Description ism:classification="U" ism:ownerProducer="USA">Europe, South</Description>
		</Term>
		<Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			<Value ism:classification="U" ism:ownerProducer="USA">MEme</Value>
			<Description ism:classification="U" ism:ownerProducer="USA">Middle East</Description>
		</Term>
		<Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			<Value ism:classification="U" ism:ownerProducer="USA">OCoc</Value>
			<Description ism:classification="U" ism:ownerProducer="USA">Oceania</Description>
		</Term>
	</cve:Enumeration>
</cve:CVE>

=== ngageoint/six-library/six/modules/c++/six.sidd/conf/schema/external/ISM-v201609/CVE/NTK/CVEnumNTKAccessPolicy.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Notices - Distribution Notice: 
           This document has been approved for Public Release and is available for use without restriction.
       -->
<cve:CVE xmlns:cve="urn:us:gov:ic:cve" xmlns:ism="urn:us:gov:ic:ism"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ism:compliesWith="USGov USIC" ism:ownerProducer="USA"
	ism:classification="U" ism:DESVersion="201609.201707" ism:ISMCATCESVersion="201609" ism:resourceElement="true"
	CVEVersion="2.1" specVersion="201508" ism:createDate="2011-09-01" xsi:schemaLocation="urn:us:gov:ic:cve ../CveSchema/CVEXml.xsd">

	<cve:IRM>
		<URN xmlns="urn:us:gov:ic:cve">urn:us:gov:ic:cvenum:ntk:accesspolicy</URN>
		<Title xmlns="urn:us:gov:ic:cve" ism:ownerProducer="USA" ism:classification="U">CVEnumNTKAccessPolicy</Title>
		<Description xmlns="urn:us:gov:ic:cve" ism:ownerProducer="USA" ism:classification="U">NTK access policy
			names. All NTK enterprise access policy URNs start with ‘urn:us:gov:ic:aces:ntk:’. Values in this CVE
			correspond to the terminating portion of NTK access policy URNs.</Description>

		<cve:Created>2010-05-30T16:52:00-04:00</cve:Created>

		<Source ism:classification="U" ism:ownerProducer="USA" xmlns="urn:us:gov:ic:cve">NTK ACES</Source>
		
		<PointOfContact ism:classification="U" ism:ownerProducer="USA" xmlns="urn:us:gov:ic:cve">
			<Name>Office of the IC CIO</Name>
			<Email>ic-standards-support@iarpa.gov</Email>
		</PointOfContact>
	</cve:IRM>

	<cve:Enumeration multivalue="false" ism:ownerProducer="USA" ism:classification="U">
		<Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			<Value ism:classification="U" ism:ownerProducer="USA">urn:us:gov:ic:aces:ntk:xd</Value>
			<Description ism:classification="U" ism:ownerProducer="USA">Exclusive Distibution</Description>
		</Term>
		<Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			<Value ism:classification="U" ism:ownerProducer="USA">urn:us:gov:ic:aces:ntk:ico</Value>
			<Description ism:classification="U" ism:ownerProducer="USA">Intelligence Community Only</Description>
		</Term>
		<Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			<Value ism:classification="U" ism:ownerProducer="USA">urn:us:gov:ic:aces:ntk:license</Value>
			<Description ism:classification="U" ism:ownerProducer="USA">License</Description>
		</Term>
		<Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			<Value ism:classification="U" ism:ownerProducer="USA">urn:us:gov:ic:aces:ntk:mn</Value>
			<Description ism:classification="U" ism:ownerProducer="USA">Mission Need Profile</Description>
		</Term>
		<Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			<Value ism:classification="U" ism:ownerProducer="USA">urn:us:gov:ic:aces:ntk:nd</Value>
			<Description ism:classification="U" ism:ownerProducer="USA">No Distribution</Description>
		</Term>
		<Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			<Value ism:classification="U" ism:ownerProducer="USA">urn:us:gov:ic:aces:ntk:oc</Value>
			<Description ism:classification="U" ism:ownerProducer="USA">Originator Controlled</Description>
		</Term>
		<Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			<Value ism:classification="U" ism:ownerProducer="USA">urn:us:gov:ic:aces:ntk:permissive</Value>
			<Description ism:classification="U" ism:ownerProducer="USA">Permissive group/individual access</Description>
		</Term>
		<Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			<Value ism:classification="U" ism:ownerProducer="USA">urn:us:gov:ic:aces:ntk:propin:1</Value>
			<Description ism:classification="U" ism:ownerProducer="USA">PROPIN for US Government Employees</Description>
		</Term>
		<Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			<Value ism:classification="U" ism:ownerProducer="USA">urn:us:gov:ic:aces:ntk:propin:2</Value>
			<Description ism:classification="U" ism:ownerProducer="USA">Explicit PROPIN</Description>
		</Term>
		<Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			<Value ism:classification="U" ism:ownerProducer="USA" regularExpression="true">urn:us:gov:ic:aces:ntk:propin:([A-Za-z][A-Za-z0-9\-_.;,():+]{1,64})</Value>
			<Description ism:classification="U" ism:ownerProducer="USA">Regex for extension of PROPIN with non-IC CIO
				access policy URN.</Description>
		</Term>
		<Term xmlns="urn:us:gov:ic:cve" ism:classification="U" ism:ownerProducer="USA">
			<Value ism:classification="U" ism:ownerProducer="USA">urn:us:gov:ic:aces:ntk:restrictive</Value>
			<Description ism:classification="U" ism:ownerProducer="USA">Restrictive group access</Description>
		</Term>
	</cve:Enumeration>

</cve:CVE>

=== ngageoint/six-library/six/modules/c++/six.sidd/conf/schema/SIDD_V3.0.0_ISM-v201609/external/ISM-v201609/CVE/ISM/CVEnumISMSAR.xml
<?xml version="1.0" encoding="utf-8"?><!-- Notices - Distribution Notice: 
           This document has been approved for Public Release and is available for use without restriction.
       --><cve:CVE xmlns:cve="urn:us:gov:ic:cve" xmlns:ism="urn:us:gov:ic:ism" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ism:compliesWith="USGov USIC" ism:ownerProducer="USA" ism:classification="U" ism:DESVersion="201609.201707" ism:ISMCATCESVersion="201609" ism:resourceElement="true" CVEVersion="2.1" specVersion="201609.201707" ism:createDate="2011-09-01" xsi:schemaLocation="urn:us:gov:ic:cve ../CveSchema/CVEXml.xsd">

    <cve:IRM>
        <URN xmlns="urn:us:gov:ic:cve">urn:us:gov:ic:cvenum:ism:sar</URN>
        <Title xmlns="urn:us:gov:ic:cve" ism:ownerProducer="USA" ism:classification="U">CVEnumISMSAR</Title>
        <Description xmlns="urn:us:gov:ic:cve" ism:ownerProducer="USA" ism:classification="U">All currently valid SAR controls from the published register. This CVE is used by @ism:SARIdentifier.</Description>

        <cve:Created>2010-03-12T11:29:00-04:00</cve:Created>

        <Source ism:classification="U" ism:ownerProducer="USA" xmlns="urn:us:gov:ic:cve">IC Systems Register and Manual</Source>
        <PointOfContact ism:classification="U" ism:ownerProducer="USA" xmlns="urn:us:gov:ic:cve">
         <Name>Office IC CIO</Name>
         <Email>ic-standards-support@iarpa.gov</Email>
      </PointOfContact>
    </cve:IRM>

    <cve:Enumeration multivalue="true" ism:ownerProducer="USA" ism:classification="U">
 <!--       
        <Term xmlns="urn:us:gov:ic:cve"
            ism:classification="U"
            ism:ownerProducer="USA">
            <Value ism:classification="U"
                ism:ownerProducer="USA"
                regularExpression="true">[A-Z_0-9\-]{1,100}</Value>
            <Description ism:classification="U" ism:ownerProducer="USA">SPECIAL ACCESS REQUIRED-XXX,Within the nickname or name of a SAR all spaces must be replaced with a "_". The XSL will restore the spaces for rendering.</Description>
        </Term>
        <Term xmlns="urn:us:gov:ic:cve"
            ism:classification="U"
            ism:ownerProducer="USA">
            <Value ism:classification="U"
                ism:ownerProducer="USA"
                regularExpression="true">[A-Z]{2,}</Value>
            <Description ism:classification="U" ism:ownerProducer="USA">SPECIAL ACCESS REQUIRED-XXX, the Digraph or Trigraph of the SAR is represented by the XXX</Description>
        </Term>
        <Term xmlns="urn:us:gov:ic:cve"
            ism:classification="U"
            ism:ownerProducer="USA">
            <Value ism:classification="U"
                ism:ownerProducer="USA"
                regularExpression="true">[A-Z]{2,}-[A-Z][A-Z0-9]+</Value>
            <Description ism:classification="U" ism:ownerProducer="USA">SPECIAL ACCESS REQUIRED-XXX, the Digraph or Trigraph of the SAR is represented by the XXX</Description>
        </Term>
        <Term xmlns="urn:us:gov:ic:cve"
            ism:classification="U"
            ism:ownerProducer="USA">
            <Value ism:classification="U"
                ism:ownerProducer="USA"
                regularExpression="true">[A-Z]{2,}-[A-Z][A-Z0-9]+-[A-Z0-9]{2,}</Value>
            <Description ism:classification="U" ism:ownerProducer="USA">SPECIAL ACCESS REQUIRED-XXX, the Digraph or Trigraph of the SAR is represented by the XXX</Description>
        </Term>
-->
    </cve:Enumeration>

</cve:CVE>
